### ISSUE TITLE
false attributes aren't written, example target="false"

### ISSUE THREAD

**Issue by titoBouzout** [ryansolid/mobx-jsx#38]
Hello Ryan! This issue I believe is related to  https://github.com/ryansolid/mobx-jsx/issues/35

If the attribute is the boolean false it gets removed instead of being set as a string. I looked into `node_modules/mobx-jsx/lib/index.js`  and there's this function 

```javascript 

function setAttribute(node, name, value) {
  if (value === false || value == null) node.removeAttribute(name);else node.setAttribute(name, value);
}
```

I have tried to see that same function on 
1. https://github.com/ryansolid/mobx-jsx
2. https://github.com/ryansolid/dom-expressions

and I cant find it, Im lost, what I am missing?

Anyway, you seem to have fixed this already on https://github.com/ryansolid/dom-expressions/blob/9b843661514f2418fe3926b67a78a6117b315cbb/packages/dom-expressions/src/client.js#L57 

Thanks!

**Comment by ryansolid** [comment]
Yeah I have fixed it. I guess it's time to do another release for MobX JSX if it isn't in there yet.

**Comment by titoBouzout** [comment]
ok thanks! I still don't understand the npm package and this repo match, but the function is nowhere to be found

**Comment by ryansolid** [comment]
The library is bundled so it only shows up when I publish. DOM Expressions is compiled into the final output so it comes down the version that is in the dev dependencies. It seems weird to do it this way but it is because I need to use the replace plugin to import mobx specific functions and still generate a treeshakable bundle. I will see what I can do in a bit. I'm trying to get Solid 1.0.0-rc.0 out the door currently.

**Comment by ryansolid** [comment]
Ok fixed in 0.15.0
